<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="118" total="120" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-07-28T14:50:05Z" name="PolicyCenter_TestSuite" finished-at="2021-07-28T14:50:05Z" duration-ms="90">
    <groups>
    </groups>
    <test started-at="2021-07-28T14:50:05Z" name="Test" finished-at="2021-07-28T14:50:05Z" duration-ms="90">
      <class name="com.Test.Guidewire.ClaimsCenter.Test_BusinessSettings_ActivityPattern">
        <test-method signature="AUT_ActivityPatterns_Validate_Page1()[pri:0, instance:com.Test.Guidewire.ClaimsCenter.Test_BusinessSettings_ActivityPattern@50d3bf39]" started-at="2021-07-28T20:20:05Z" name="AUT_ActivityPatterns_Validate_Page1" finished-at="2021-07-28T20:20:05Z" duration-ms="36" status="FAIL">
          <exception class="com.codoid.products.exception.FilloException">
            <message>
              <![CDATA[Workbook is not found - C:\Users\labor\git\blackcomb\testdata\null.xlsx]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.codoid.products.exception.FilloException: Workbook is not found - C:\Users\labor\git\blackcomb\testdata\null.xlsx
	at com.codoid.products.fillo.Fillo.getConnection(Fillo.java:46)
	at com.Utils.Selenium.Selenium_Utils_DataBase.getConnection(Selenium_Utils_DataBase.java:26)
	at com.Utils.Selenium.Selenium_Utils_DataBase.getData_MSExcel_WorkSheet_Fillo(Selenium_Utils_DataBase.java:109)
	at com.pages.Guidewire.GW_CM_PC_BC_CC_Login.login_ClaimsCenter_User(GW_CM_PC_BC_CC_Login.java:92)
	at com.Test.Guidewire.ClaimsCenter.Test_BusinessSettings_ActivityPattern.AUT_ActivityPatterns_Validate_Page1(Test_BusinessSettings_ActivityPattern.java:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- com.codoid.products.exception.FilloException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AUT_ActivityPatterns_Validate_Page1 -->
        <test-method signature="AUT_ActivityPatternDetail_Validate_3pointcontactEmployee()[pri:0, instance:com.Test.Guidewire.ClaimsCenter.Test_BusinessSettings_ActivityPattern@50d3bf39]" started-at="2021-07-28T20:20:05Z" name="AUT_ActivityPatternDetail_Validate_3pointcontactEmployee" finished-at="2021-07-28T20:20:05Z" duration-ms="1" status="FAIL">
          <exception class="com.codoid.products.exception.FilloException">
            <message>
              <![CDATA[Workbook is not found - C:\Users\labor\git\blackcomb\testdata\null.xlsx]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.codoid.products.exception.FilloException: Workbook is not found - C:\Users\labor\git\blackcomb\testdata\null.xlsx
	at com.codoid.products.fillo.Fillo.getConnection(Fillo.java:46)
	at com.Utils.Selenium.Selenium_Utils_DataBase.getConnection(Selenium_Utils_DataBase.java:26)
	at com.Utils.Selenium.Selenium_Utils_DataBase.getData_MSExcel_WorkSheet_Fillo(Selenium_Utils_DataBase.java:109)
	at com.pages.Guidewire.GW_CM_PC_BC_CC_Login.login_ClaimsCenter_User(GW_CM_PC_BC_CC_Login.java:92)
	at com.Test.Guidewire.ClaimsCenter.Test_BusinessSettings_ActivityPattern.AUT_ActivityPatternDetail_Validate_3pointcontactEmployee(Test_BusinessSettings_ActivityPattern.java:399)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- com.codoid.products.exception.FilloException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AUT_ActivityPatternDetail_Validate_3pointcontactEmployee -->
      </class> <!-- com.Test.Guidewire.ClaimsCenter.Test_BusinessSettings_ActivityPattern -->
    </test> <!-- Test -->
  </suite> <!-- PolicyCenter_TestSuite -->
</testng-results>
